name: recipe_suggester_app
description: A Flutter app that suggests recipes based on available ingredients and allows users to buy food.

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  flutter_spinkit: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/tomato.png
    - assets/onion.png
    - assets/potato.png